spring:
  application:
    name: demo
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3307/demo 
    driverClassName: org.mariadb.jdbc.Driver 
    username: root 
    password:  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect 
