spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb # URL de conexão para o banco MariaDB local na porta 3306.
    driverClassName: org.mariadb.jdbc.Driver # Define o driver JDBC para MariaDB.
    username: root # Nome de usuário para conexão com o banco.
    password: your_password # Senha para conexão com o banco.
  jpa:
    hibernate:
      ddl-auto: update # Configura o Hibernate para atualizar o esquema do banco automaticamente.
    show-sql: true # Habilita a exibição das consultas SQL no console.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # Define o dialeto do Hibernate para MariaDB.
